examples/raspberry-pi.rs
src/lib.rs

Add pwm_Channel global enum for user,
Fix the pwm_set_value, now with inputs (channel and value)
Add pwm_set_value_mult, which set values for a array, &[ch1,ch2,ch3]
Update example and add new one with random values.

Update pwm_set_value with inputs and global enum channel

---

src/lib.rs

This commit fix the behavior reported here:
[Error at first use of each pin from GPIO](https://github.com/bluerobotics/navigator-rs/issues/5)
Also a thread was opened on linux_embedded_hal for further investigation.

src: lib: bug fix: Add delay between gpio export and direction

---

src/lib.rs

From:
[Ardupilit-PCA9685](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_Linux/RCOutput_PCA9685.cpp)
and
Oe_pin should be defined to enable pwm outputs.

pwm: Add oe_pin to pwm methods

---

examples/raspberry-pi.rs
src/lib.rs

Like we did on navigator-lib, channels should be called with Ch*,
As here:
```
PwmChannel::Ch1
AdcChannel::Ch1
```
*As pointed on Raom meeting, DiffChannels wasn't added to the navigator AdcChannel
Also add more documentation files for set_pwm_channel_value related functions.

Create a channel stantard

---

src/lib.rs

Needs rebase over:
Change adc scale according the schematics, using:
±4.096 V with LSB - 125 μV
[FullScale Register](https://www.ti.com/lit/ds/symlink/ads1115.pdf#page=17)
Change the output of adc to a converted value,

Adc upgrades

---

src/lib.rs

We can just remove this functions, or keep then as follows.
it's just an use case of `set_pwm_channel_value` with `PwmChannels::All`

Remove reduntant functions set_pwm_all_on & off

---

src/lib.rs

Merge pwm_enable methods to a single one.
Corrects the open milestone issue:

src: lib: pwm: Merge pwm_enable methods

---

src/lib.rs

*Needs Merge & Rebase:
Merge set_led methods to a single one.
Corrects the open milestone issue:

Merge functions set_led

---

src/lib.rs

The sensors readings now follows the aeronautical frame system, right-handed, Z-axis down.
https://www.mathworks.com/help/aeroblks/about-aerospace-coordinate-systems.html
Corrects the open milestone issue:

src: lib: Change the sensor readings axes to navigator's standard

---

.github/workflows/action.yml

This new deploy action able our repo to automatically deploy on crates.io.
It also upgrade the current version of the crate and stores it as a commit.
It's triggered by releases with a tag name as: "x.x.x"
This PR closes the last milestone issue for first release.

Add automatic deploy & version upgrade

---

src/lib.rs

The current pca9685 library is using enable()/disable() to change SLEEP bit,
And current navigator.pwm_enable() is setting both software (pca9686 sleep bit) and HW (OE pin) to enable/disable.
This create an undisered behavior, if user disable and re-enable he needs to change at least some channel again.
With this PR enable/disable just work directly as expected.

Fix pwm enable/disable

---

src/lib.rs

Allows user to:
```
println!("Creating your SensorData cache!");
let sensor_data_lock = Arc::new(RwLock::new(navigator_rs::SensorData::default()));
```

Add: Add default for SensorData and inner structures.

---

Cargo.toml
benches/bench.rs

A fast way to benchmark our functions, seems work pretty fine locally and on hosted-ci-runner.
cargo bench --jobs 1 --bench bench | tee output.txt
```
new                     time:   [190.92 ms 190.98 ms 191.04 ms]
Found 12 outliers among 100 measurements (12.00%)
8 (8.00%) low severe
2 (2.00%) high mild
2 (2.00%) high severe
init                    time:   [328.32 ms 328.46 ms 328.60 ms]
Found 16 outliers among 100 measurements (16.00%)
1 (1.00%) low severe
1 (1.00%) low mild
1 (1.00%) high mild
13 (13.00%) high severe
read_adc                time:   [9.9898 ms 10.011 ms 10.030 ms]
Found 19 outliers among 100 measurements (19.00%)
13 (13.00%) low severe
4 (4.00%) low mild
2 (2.00%) high severe
read_adc_all            time:   [39.829 ms 39.941 ms 40.044 ms]
Found 21 outliers among 100 …
```

Add: Benchmarking with Criterion

---

.github/workflows/action.yml

Add perfomance check btwn master pr [1]

---

.github/workflows/action.yml

Add perfomance check btwn master pr [2]

---

.github/workflows/action.yml

Fix: CI not fail with benchmark job faillures

---

src/lib.rs

Needs:
Add:
1. set_pwm_channels_duty_cycle()
2. set_pwm_channels_duty_cycle_values()

Add: Add pwm_duty_cycle multichannel

---

src/lib.rs

Known issue faced and solved on SPI's CSs and UserLED pins.
Details:

Fix : Leak sensor : Set gpio Input on first time without need sudo

---

Cargo.toml

Normal users should use docs.rs

Cargo: Fix documentation link

---

.github/workflows/action.yml

Need:
Closes:
https://github.com/bluerobotics/navigator-rs/issues/76
Improove ( a lot ) CI benchmarking process.
Now Benchmarking binary is compiled on cross-rs.
Now:
Before:

chore: Improve CI benchmark speed

---

.github/workflows/action.yml
benches/bench.rs
examples/rainbow.rs
examples/raspberry-pi-threads.rs
examples/raspberry-pi.rs
src/ads1115.rs
src/ak09915.rs
src/bmp280.rs
src/icm20689.rs
src/leak.rs
src/led.rs
src/lib.rs
src/pca9685.rs
src/peripherals.rs
src/rgb.rs

Major rework that:
- break each sensor as a module
- Use builder pattern for board definition
- change some api to use higher level functions
- allow multiple board definitions and combinations
- next PR

rework drivers

---

src/icm20689.rs
src/leak.rs
src/led.rs
src/pca9685.rs

{icm20689, leak, led, pca9685}: Move from 30 to 60ms to wait pin configuration

---

src/bmp390.rs
src/lib.rs
src/peripherals.rs

bmp390: Add first version

---

src/lib.rs

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

lib: Add support to navigator v2 in pi4 and navigator v1 to pi5
